### PR TITLE
Added Python requirements

### PR DESCRIPTION
**Pull request by jhoelzl**
to run python demo/python/porcupine_demo.py

### CODE REVIEW

**Comment by kenarsa** [comment]
Thanks for PR. Unfortunately, CI fails when trying to install PyAudio. We had the same issue and ended up installing it using apt-get. How did you install PyAudio? pip?

**Comment by jhoelzl** [comment]
Hi, i think you need to install portaudio before installing pyaudio with "pip".

**Comment by kenarsa** [comment]
Got it. That's why we decided not to add it as a requirement and just use the aptitude package as also mentioned in official page here: https://people.csail.mit.edu/hubert/pyaudio/

**Comment by jhoelzl** [comment]
Okay. But at least you could add "numpy" to requirements.txt.

**Comment by kenarsa** [comment]
Definitely, let's do that, please :)
Sorry, I first commented and then updated it.

**Comment by kenarsa** [comment]
@jhoelzl, could you please do your change like this? https://github.com/Picovoice/Porcupine/pull/34
Then, we don't need to worry about CI failing. Thanks. You can keep both dependencies.

**Comment by jhoelzl** [comment]
@kenarsa i removed the version numbers. Or did I misunderstand you?

**Comment by kenarsa** [comment]
Hi @jhoelzl 

That helps. But also I meant let's have a separate requirements file for demo under demo/python. Similar to what @MatthewScholefield  has done https://github.com/Picovoice/Porcupine/pull/34/files

It does not break CI anymore this way. Thanks a lot.

**Comment by jhoelzl** [comment]
@kenarsa , okay i got it (finally) :)

**Pull request merged**
